# Generated by Django 5.2.7 on 2025-11-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0006_feed_last_successful_fetch"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelayMetadata",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "etag",
                    models.CharField(
                        help_text="Global ETag for HTTP caching", max_length=16
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        help_text="Global Last-Modified timestamp for HTTP caching"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Relay Metadata",
                "verbose_name_plural": "Relay Metadata",
            },
        ),
    ]
