# Generated by Django 5.2.8 on 2025-11-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0007_relaymetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="include",
            field=models.CharField(
                blank=True,
                help_text="Post being boosted/shared (URL#ID format)",
                max_length=300,
            ),
        ),
    ]
