# Generated by Django 5.2.6 on 2026-01-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, help_text='User birthday in YYYY-MM-DD format', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, help_text='Space-separated language codes (ISO 639-1)', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='User location (city, country, etc.)', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='pinned',
            field=models.CharField(blank=True, help_text='Pinned post ID (timestamp)', max_length=50),
        ),
    ]
