# Generated by Django 6.0.7 on 2026-07-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_profile_birthday_profile_language_profile_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingWebmention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField(help_text='Post URL (feed#post_id) containing the link', max_length=500)),
                ('target', models.URLField(help_text='External URL the post links to', max_length=500)),
                ('endpoint', models.URLField(blank=True, help_text='Discovered Webmention endpoint', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('no_endpoint', 'No endpoint')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('response_code', models.IntegerField(blank=True, help_text='HTTP status of the last delivery attempt', null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('source', 'target')},
            },
        ),
    ]
