# Generated by Django 6.0.7 on 2026-07-17 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("feeds", "0011_outgoingwebmention"),
    ]

    operations = [
        migrations.CreateModel(
            name="BridgedActivityPubAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        help_text="Normalized handle in user@instance form (lowercase)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "actor_url",
                    models.URLField(
                        help_text="ActivityPub actor document URL", max_length=500
                    ),
                ),
                (
                    "outbox_url",
                    models.URLField(
                        blank=True, help_text="ActivityPub outbox URL", max_length=500
                    ),
                ),
                (
                    "last_refreshed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful fetch from the origin",
                        null=True,
                    ),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(
                        help_text="Last time a client requested this virtual feed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.OneToOneField(
                        help_text="Profile that stores the bridged data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activitypub_bridge",
                        to="feeds.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["handle"],
            },
        ),
        migrations.CreateModel(
            name="BridgedRssFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="URL of the RSS/Atom feed",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "last_refreshed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful fetch from the origin",
                        null=True,
                    ),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(
                        help_text="Last time a client requested this virtual feed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.OneToOneField(
                        help_text="Profile that stores the bridged data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rss_bridge",
                        to="feeds.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["source_url"],
            },
        ),
    ]
